### ISSUE TITLE
WebID Profile Work Item

### ISSUE THREAD

**Issue by csarven** [solid/webid-profile#15]
To introduce WebID Profile as a Work Item and continuing with the development:

PR updating https://github.com/solid/specification/blob/main/index.html to include an entry for the WebID Profile spec to appear at https://solidproject.org/TR/

The link to the work item can either be https://github.com/solid/webid-profile/blob/main/notes/pre-final-draft.md or URL of a document that uses a spec template / formatted as such with "Editor's Draft" (ED) status. Later on it can be the link to the Technical Report (TR) version (once approved).

At some point, there should be a ED URL (e.g., `https://solid.github.io/webid-profile/` or perhaps more specific like `https://solid.github.io/webid-profile/discovery` if the group finds small related specs will be published in different documents. Alternatively, if the group prefers to publish the ED at `https://solidproject.org/ED/webid-profile` , that's also possible but then the work will have to continue in https://github.com/solid/specification . I suggest working on the ED in this solid/webid-profile repo for the time being but the group can decide.)

To propose a versioned release of the spec, there needs to be a PR to https://github.com/solid/specification so that it can be published at e.g., `https://solidproject.org/TR/webid-profile` . See https://github.com/solid/specification/blob/main/CONTRIBUTING.md for mode details on that. Happy to fill in gaps here/gitter etc.. and update the guide as necessary.

The links in https://github.com/solid/specification/blob/main/index.html can be changed any time e.g., when going from ED URL to TR URL.

**Comment by VirginiaBalseiro** [comment]
Can we close this as done?

**Comment by csarven** [comment]
Currently using https://solid.github.io/webid-profile/ as the ED and it is listed as a Work Item at https://solidproject.org/TR/ .
