### ISSUE TITLE
Separate the definition of a concrete index from the profile 

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/webid-profile#35]
### Background: Orthogonal features live in different documents

A general principle within the collection of Solid specs is to describe orthogonal concerns in different documents.
For instance, WAC is defined in a separate document of itself.

### Observation: Profiles and indexes seem orthogonal

The current Solid WebID Profile defines a specific kind of index, namely the type index.

Whereas indexes are important and crucial, it seems that they are an **orthogonal concern**:
indexes exist independently of profiles.
Furthermore, I expect different kinds of indexes to be defined in the near future,
whereas we probably want to strive for a profile document with a long lifetime.

Hence, I am making the following proposal for type indexes.

### Proposal: move type indexes into a separate document

Required steps:

- Create a separate specification document for the type index (or indexes in general)
- Explain in the profile document that profiles MAY (or SHOULD, or MUST) contain an index.
  - Link here to the type index specification

Happy to help realize this proposal via a PR. However, I first wanted to start the discussion on this.

**Comment by jeff-zucker** [comment]
I don't have an objection to doing it this way. @timea-solid - thoughts?

**Comment by timea-solid** [comment]
@RubenVerborgh we discussed it over at the meeting and we have some further questions:
1) what kind of indexes do you think of? Is it going in the direction of automatically generated indexes for search purposes?
2) spec structure-wise - how would this separation looks like? What version would it have?

**Comment by jeff-zucker** [comment]
@timbl mentioned the phrase "Instance Discovery".  This suggests to me a way to distinguish which parts go in which spec.  The WebID Profile spec covers discovery of the typeIndex documents.  The Type Index spec covers discovery of the type registration instances which are found in the type index documents.  We would not need much overlap - a sentence or two can describe how to find the type index documents and generally what they contain and leave all the rest to the type index spec.

**Comment by RubenVerborgh** [comment]
Hey @timea-solid!

> we discussed it over at the meeting and we have some further questions:

Thanks a lot! I'll write some proposed answers below.

> what kind of indexes do you think of?

There can be many different indexes for different purposes.
These are a couple of concrete examples:
- subject indexes
- property indexes
- shape indexes
- full-text indexes
- cross-Pod indexes
- …

Type indexes cover the specific case where the predicate is `rdf:type`. And that's an interesting case, but there are many more ways that we'll see in the future.

> Is it going in the direction of automatically generated indexes

Presumably this is about whether the server, client, or an agent maintains the indexes. I'd say this is an orthogonal question, in the sense that all options are possible for each index. So it is up the specifications of those indexes to define that (or leave it open so multiple options are possible).

> for search purposes?

There are many purposes; search is just one of them.
For instance, even though the type index has been designed for discovery, we are using it for query optimization as well. And more purposes can be imagined.

> spec structure-wise - how would this separation looks like?

I'd imagine:
- one spec detailing the type index
  - which is independent of the profile spec
- one spec detailing expectations for a profile document
  - which includes a type index, so the profile spec links to the type index

So that matches with what @jeff-zucker wrote above. (Thanks, Jeff!)

> What version would it have?

They can be independently versioned.

**Comment by timea-solid** [comment]
Thanks @RubenVerborgh for filling the gaps. 
I had a good hunch of the type of indexes you had in mind.
In general, the team is for your proposal. The only remaining question is: is now the time for it?

**Comment by RubenVerborgh** [comment]
Thanks, @timea-solid!

> is now the time for it?

Well, given that the profile spec seems about to be published, I think it's best that it is directly published in an appropriate manner, so with orthogonal concerns separated.

Note that my proposal is currently only this separation, such that future extensions to indexes are possible. I am not proposing for these future extensions to happen now.

If this separation is accepted, I'm happy to help realize it.

**Comment by csarven** [comment]
Besides the consideration to separate the documents:

@RubenVerborgh (as well as anyone else that's interested), I can only encourage you to consider committing to a specific role for the new document, i.e., primarily as an editor and/or author.

**Comment by RubenVerborgh** [comment]
If the team accepts to proceed, I'm happy to perform the split and act as a temporary editor.

**Comment by woutermont** [comment]
@RubenVerborgh, can you keep us posted as to where (and/or when) we can contribute more to the new index doc? Thanks!

**Comment by timea-solid** [comment]
@woutermont the new home of the Type Index is: https://github.com/solid/type-indexes Feel free to open discussions or git issues on the new repo.
