### ISSUE TITLE
solid:owner and solid:account

### ISSUE THREAD

**Issue by jeff-zucker** [solid/webid-profile#44]
We have not mentioned these two predicates and they are actually pretty important from a discovery point of view.  If you arrive at a pod without knowing the WebID of the owner, these predicates are the only ways to find out [EDIT, not true, space:storage predicate implies ownership, I believe].

I think that we should say that, unless there are privacy concerns, there SHOULD be a `solid:owner` predicate in the Solid Profile Document and that, for purposes of discovery, an app SHOULD look for that predicate and if not found, travel up the container tree until you reach the pod root and look for a `solid:account` predicate.

**Comment by jeff-zucker** [comment]
Some reasons this might not be a good idea to includee these predicates :  I have not spoken to a single implementer who makes use of these predicates.  And too, a triple like `<?WebID> space:storage </>.` conveys the same information.  So maybe it is just  as well to skip this.

**Comment by VirginiaBalseiro** [comment]
What if the owner of the Pod is not the subject of the WebID document? Example: I get a pod from the immigration office in Hamburg but they own it, I am not allowed to edit anything in it to prevent me from tampering with important data, but they use it as storage for my residency permit information. Maybe "associated WebID" would be better than "owner" in this case?

**Comment by jeff-zucker** [comment]
I think we should drop this one as it overlaps with the storage predicate.  I don't know why you would have a                   WebID in the Hamburg situation - wouldn't it  all be under  their WebID with a container they give read permission to your WebID?

I'll close this, but If you think there should be a an open question about using solid:owner, please feel free to reopen.
