### ISSUE TITLE
Document use cases for Solid profile

### ISSUE THREAD

**Issue by VirginiaBalseiro** [solid/webid-profile#55]
Document the different use cases for a Solid profile.

Note: this should include discovery of: 
- storage
- inbox

**Comment by timbl** [comment]
5 use cases: 

 1. In a Solid chat, someone asks to be included in a group.
  2. I drag their identity from the chat 'author' field into a browser tab to look at their profile
 3. I check that the profile is one who asserts that say
    - they are someone I know and recognize from the picture OR
    - they are in an existing group of people I trust OR
    - other people in the chat express trust OR
    - they have CV which is impressive and I trust it is right
    - They have a VC indivating a trustworthy status
5. I drag an icon from the profile (or from the chat) into the group in my contacts and their webID gets added to the group.
6. They get access to stuff the group has access to 

The point of these use cases is that while the technical identity (if you like) is  concerned, the the reasons it is useful
and actually used is the collaborative, professional or social identity.   

As we discuss this on Github and Gitter of course within a github organization we have to admit that all this interaction and permissioning is based on similar reputation-based ways of working. We should be able to port this all to Solid apps.
