### ISSUE TITLE
Do not redefine "WebID" or "WebID Profile Document", clearly define "profile"

### ISSUE THREAD

**Issue by woutermont** [solid/webid-profile#61]
The past few days, I've had some discussions with members of the CG about the use of the terms 'WebID', 'WebID Profile', 'Solid Profile' and the ambiguously plain 'profile' (see [gitter.im/solid/specification](https://gitter.im/solid/specification) and [gitter.im/solid/webid-profile](https://gitter.im/solid/webid-profile), Oct 20-23).

Let's start by agreeing that the meaning of the two first terms, 'WebID' and 'WebID Profile', is fixed by the WebID 1.0 2014 draft spec: 

> **WebID**
A WebID is a URI with an HTTP or HTTPS scheme which denotes an Agent [...] the URI without the fragment [... or the 303] Location header URI [of which is] referring to the Profile Document.
>
> **WebID Profile or Profile Document**
A WebID Profile is an RDF document which uniquely describes the Agent denoted by the WebID in relation to that WebID. [...]

---

Continuing, most people will intuïtively disagree with this: _the WebID Profile is not a profile in the sense of a social media profile_. I can be convinced otherwise, but neither the WebID 1.0 spec, nor any of the CG pages around it, specify it as such. To the contrary, it is many times specified in ways that are quite contradictory to such an idea, highlighting the Profile's role as a central extendable entrypoint for different technological mechanisms. 

Consider the following statement, which is the only appearance of the term 'social' in those pages (not counting variations of 'the Social Web').

> A description of the WebID can be found in the Profile Document, a type of web page that any Social Network user is familiar with.

For starters, this is found in the non-normative introduction. Besides the fact that the first part of the statement is incorrect (the document describes the _referent_ of the WebID, not the WebID itself, as clarified in [section 4](https://www.w3.org/2005/Incubator/webid/spec/identity/#overview)), it immediately clashes with the sentence following it, as well as many similar statements in normative sections of the spec:

> A WebID Profile Document [...] must be available as text/turtle [...] but may be available in other RDF serialization formats [...] if requested through content negotiation.

> The WebID Profile gives the sense of the WebID: its RDF Graph contains a Concise Bounded Description of the WebID such that this subgraph forms a definite description of the referent of the WebID, that is, a description that distinguishes the referent of that WebID from all other things in the world.

The only requirements we find there are that WebID Profiles contain enough information to uniquely identify the referent (e.g. a serial number, URN, UUID, or civilian registration number; i.e. not necessarily a name and address), and that they can be served as Turtle; NOT as a nicely formatted HTML page which "any Social Network user is familiar with." Nor the spec, nor I, says that this can/should not be done; rather, it indicates that the WebID Profile is not, in itself, a social media style profile.

From this, I would conclude that
- [ ] we should not use the ambiguous term "profile" without clear qualification;
- [ ] we should not use the term "WebID Profile" when we mean something more specific;
- [ ] we should therefore change the name of this document and its repo;
- [ ] we should inform users and developers having these wrong assumptions, so that they will not be caught off guard when something breaks.

**Comment by jeff-zucker** [comment]
Agree that we should not  redefine WebID or WebID Profile Document.  Agree that we should not use the word "profile" without a clear definition. We will probably introduce the concept of a Solid WebID Profile Document.  This repo is the solid/webid-profile repo which I believe is the appropriate name for repo about that document.

**Comment by woutermont** [comment]
A question then: what is our way of action when a new (RDF-based) dereferencable identifier comes into play, say "SomeID"? Does the "Solid WebID Profile" spec concern SomeID documents as well? Do we create an identical spec called "Solid SomeID Profile"?

**Comment by jeff-zucker** [comment]
Well, that is an interesting question.  The reason that I believe we need the word WebID in "Solid WebID Profile Document" is that it is not just any document,  it is one verifiable based on the WebID.

**Comment by woutermont** [comment]
Of course a Solid Profile Document is not just _any_ document. But for all intents and purposes, it seems to suffice for it to be an RDF document to which the identifier dereferences, and which contains certain specific triples.

By not specifying a single choice, a Solid Profile spec would be _orthogonal_ to the concrete choice of identifier (WebID, DID, SomeID ...), enabling all of the flexibility, extendability and compatibility we love in orthogonalk specs.

**Comment by jeff-zucker** [comment]
It's worth thinking about.  I am not opposed to changing the name.

**Comment by jeff-zucker** [comment]
How about you raise the name change as an issue on it's own.  You can just refer back here, but it's a separate thing from the other parts of this current issue which I will close since we are agreed that we will not redefine WebID or WebID Profile and that we'll clarify our use of the word profile.
