### ISSUE TITLE
Refer to "Solid Profile Document" not "Solid WebID Profile Document" to leave room for DID, etc.

### ISSUE THREAD

**Issue by woutermont** [solid/webid-profile#67]
> @jeff-zucker How about you raise the name change as an issue on it's own. (#61)

I made this issue bigger, because it is not the name in itself, but rather the lack of orthogonality, that is the problem here. I repeat my comment from the referred issue:

> [A] Solid Profile Document is not just any document, [but] for all intents and purposes, it seems to suffice for it to be **an RDF document to which the identifier dereferences, and which contains certain specific triples**. [...] By not specifying a single choice, a Solid Profile spec would be orthogonal to the concrete choice of identifier (WebID, DID, SomeID ...), enabling all of the flexibility, extendability and compatibility we love in orthogonal specs.

Not much more to be said. I hereby propose to change the references to WebID to a concrete functional requirement in line with the emphasised part of the quote (and to rename this document accordinly).

**Comment by csarven** [comment]
There is no urgency for such abstraction.

When different types of identifiers are used for agents in the Solid ecosystem accompanied with adequate implementation experience, we can then consider whether an abstraction is needed.

**Comment by woutermont** [comment]
Never said this was urgent :)

The abstraction could, however, greatly reduce the confusion between the Solid Profile and the underlying identification system (i.e. the current WebID Profile).

Also, I did write this issue in close connection to the suggestion that this spec does not fit in the Solid ecosystem (https://github.com/solid/webid-profile/issues/66). With that in mind, this spec is not bound to the types of identifiers used in Solid.

**Comment by csarven** [comment]
The abstraction could also unnecessarily complicate things. (I'm not compelled to debate this further but you and others are welcome to.)

I don't share your confusion. Solid WebID Profile is intended to describe (or specialise if you will) WebID profile in the context of Solid based on publishing practises and running code (for a decade, if not longer, depending on how one wants to time things).

**Comment by woutermont** [comment]
Okay. Then I'll yield and suggest to put this issue on ice untill the time for abstraction is there, unless other people want to continue debating.
