### ISSUE TITLE
Revise conformance section

### ISSUE THREAD

**Issue by VirginiaBalseiro** [solid/webid-profile#89]

**Comment by csarven** [comment]
Use the Conformance sections from https://solidproject.org/TR/protocol#conformance or https://solidproject.org/TR/notifications-protocol#conformance as template.

1. Normative and Informative Content -- this section can be copy/pasted for starters.
2. Specification Category -- copy/paste but have a look at the concepts under http://www.w3.org/ns/spec#SpecificationCategory .
3. Classes of Products -- work on this section alongside the Terminology section ( https://github.com/solid/webid-profile/issues/21 ). Reuse terms from the Terminology section. Have a look at http://www.w3.org/ns/spec#ClassesOfProducts to reuse but it should probably be new/specific concepts where the Spec Terms' concept could be a broadMatch. See notifications-protocol's source
4. Interoperability -- pair/set of classes of products that are intended interop.

If this section is nailed down well, the rest of the spec will "write itself"(TM). I promise! :) There'll surely be revisions on the concepts and descriptions, but everything will make a lot of sense. Seeing the spec as it truly is.

![matrix-seeing-it-as-it-truly-is](https://github.com/solid/webid-profile/assets/429987/c6d75c80-d54a-475c-8952-d1a53edc0d1f)

 (I'll detail the above in solid/specification CONTRIBUTING.md later)
